### ISSUE TITLE
Cannot instantiate beetlsql mapper interface when inject

### ISSUE THREAD

**Issue by leeaee** [actframework/act-aaa-plugin#11]
1. Implement a <code>SecurityService</code> extends from <code>ActAAAService.Base</code>.
2. Inject a beetsql mapper into <code>SecurityService</code>
3. ACT start failed with exception:
```log
2017-08-03 17:10:12,262 WARN  [jobs-thread-1] [act.job._Job] - error executing job register-singleton-instances
org.osgl.inject.InjectException: Cannot instantiate interface cc.bable.data.mapper.AdminMapper(mapper)
	at org.osgl.inject.Genie.findProvider(Genie.java:657)
	at org.osgl.inject.Genie.fieldInjector(Genie.java:797)
	at org.osgl.inject.Genie.fieldInjectors(Genie.java:784)
	at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:725)
	at org.osgl.inject.Genie.buildProvider(Genie.java:705)
```
Code:
AdminMapper.java
```java
public interface AdminMapper extends BaseMapper<Admin> {
    Admin findByName(@Param(value = "loginName") String loginName);
} 
```
```java
public class SecurityService extends ActAAAService.Base<Admin> {
    private static final String USER_KEY = "loginName";
    @Inject
    private AdminMapper mapper;
    @Override
    protected String userKey() {
        return USER_KEY;
    }
...
}
```

**Comment by greenlaw110** [comment]
It can now overwrite the following two methods in your `SecurityService` to allow act-aaa to work with act-beetlsql:

```java

        protected USER_TYPE findUser(String username) {
            return userDao.findOneBy(_userKey(), username);
        }

        protected void initUserDao(Class<USER_TYPE> userType) {
            this.userDao = Act.app().dbServiceManager().dao(userType);
        }

```
